language: c

os:
  - osx

compiler:
  - clang

before_install:
  - brew --version
  - "brew update 2>&1 > /tmp/brew-update.txt || (cat /tmp/brew-update.txt && false)"
  - brew list --versions

install:
  - brew reinstall
    Gsasl
    bison
    ccache
    cpanm
    libevent
    maven
    openssl
    protobuf
    protobuf-c
    python
    snappy
    thrift
  - brew outdated libyaml || brew upgrade libyaml
  - brew outdated json-c  || brew upgrade json-c
  - brew outdated boost   || brew upgrade boost
  - brew outdated maven   || brew upgrade maven
  - brew install iproute2mac
  - brew list --versions
  - sudo pip install pycrypto
  - sudo cpanm install JSON

before_script:
  - mvn apache-rat:check
  - cd $TRAVIS_BUILD_DIR
  - ./configure

script:
  - make -j$(sysctl -n hw.ncpu)
  - make feature-test
  - make feature-test-clean

branches:
  except:
    - legacy
